title       = "cx"
baseURL     = "https://chaoxing-cli.tamnd.com/"
description = "Browse Chaoxing university courses"
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/chaoxing-cli"
